config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    root 'homes#top'
    get  'about',   to: 'homes#about'

    resource  :customers,     only:[:show,:edit,:update] do
        get   'quit_confirm', on: :collection
        patch 'quit',         on: :collection
    end

    resources :shipping_addresses, except:[:new,:show]
    resources :items,              only:[:index,:show] do
      get :autocomplete_item_name, :on => :collection
    end

    resources :cart_items, except:[:new,:edit,:show] do
      delete 'destroy_all', on: :collection
    end

    resources :orders, only:[:create,:index,:show] do
      collection do
        get  'information'
        get  'thankyou'
        post 'purchase'
      end
    end
  end

  namespace :admin do
    resources  :customers,   except:[:new,:destroy,:create]
    resources  :genres,      except:[:new,:destroy,:show]
    resources  :items,       except:[:destroy]
    resources  :orders,      only:[:index,:show,:update]
    resources  :order_lists, only:[:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :postcode
    validates :address
    validates :phone_number
  end

  validates :postcode, format: {with: /\A[0-9]{7}\z/}
  validates :phone_number, format: {with: /\A[0-9]{10,11}\z/}

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  #追加メソッド
  def join_name
    self.last_name + " " + self.first_name
  end

  def join_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  def join_address
    "〒" + self.postcode + " " + self.address
  end

  #退会していたらtrueを返す
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  #すでに商品をカートに入れているか確認
  def item_include?(item)
    cart_items.where(item_id: item.id).exists?
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers=Customer.page(params[:page]).per(10)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice]="会員情報を更新しました"
      redirect_to admin_customer_path(@customer.id)
    else
      render "admin/customers/edit"
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :email, :phone_number, :is_deleted)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_path
  end

  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   customers_path
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= render 'layouts/errors', obj: @customer %>

<div class="container mt-5">
  <div class="row">
    <div class="mx-2 col-8">

      <h5 class="two-line-heading"><%= @customer.join_name %>さんの会員情報編集</h5>
      <%= form_with model:@customer,  url:admin_customer_path, local:true do |f| %>

        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td><%= f.label :氏名 %></td>
              <td><%= f.text_field :last_name %></td>
              <td><%= f.text_field :first_name %></td>
            </tr>
            <tr>
              <td><%= f.label :フリガナ %></td>
              <td><%= f.text_field :last_name_kana %></td>
              <td><%= f.text_field :first_name_kana %></td>
            </tr>
            <tr>
              <td><%= f.label :郵便番号 %></td>
              <td><%= f.text_field :postcode %></td>
            </tr>
            <tr>
              <td><%= f.label :住所 %></td>
              <td><%= f.text_field :address %></td>
            </tr>
            <tr>
              <td><%= f.label :電話番号 %></td>
              <td><%= f.text_field :phone_number %></td>
            </tr>
            <tr>
              <td><%= f.label :メールアドレス %></td>
              <td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <td><%= f.label :会員ステータス %></td>
              <td><%= f.radio_button :is_deleted, "false" %>有効  <%= f.radio_button :is_deleted, "true" %>退会</td>
            </tr>
          </tbody>
        </table>

        <div class="actions">
          <%= f.submit "変更を保存",class: "btn-flat-success" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-3">
      <h5 class="two-line-heading">会員一覧</h5>
      <table class="table table-hover w-100">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.join_name,admin_customer_path(customer.id), class:'link_animation' %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted %>
                  <p class="text-secondary"><%= "退会" %></p>
                <% else %>
                  <p class="text-success"><%= "有効" %></p>
              	<% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= paginate @customers %></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="mx-2 col-8">
      <h5 class="two-line-heading"><%= @customer.join_name %>さんの会員詳細</h5>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.join_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.join_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postcode %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_deleted %>
                <p class="text-secondary"><%= "退会" %></p>
              <% else %>
                <p class="text-success"><%= "有効" %></p>
            	<% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <%= link_to "編集する",edit_admin_customer_path(@customer.id),class: "btn-flat-success" %>
      <%= link_to "注文履歴一覧を見る",admin_orders_path(customer_id: @customer.id),class: "btn-flat-primary" %>

    </div>
  </div>
</div>