config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    root 'homes#top'
    get  'about',   to: 'homes#about'

    resource  :customers,     only:[:show,:edit,:update] do
        get   'quit_confirm', on: :collection
        patch 'quit',         on: :collection
    end

    resources :shipping_addresses, except:[:new,:show]
    resources :items,              only:[:index,:show] do
      get :autocomplete_item_name, :on => :collection
    end

    resources :cart_items, except:[:new,:edit,:show] do
      delete 'destroy_all', on: :collection
    end

    resources :orders, only:[:create,:index,:show] do
      collection do
        get  'information'
        get  'thankyou'
        post 'purchase'
      end
    end
  end

  namespace :admin do
    resources  :customers,   except:[:new,:destroy,:create]
    resources  :genres,      except:[:new,:destroy,:show]
    resources  :items,       except:[:destroy]
    resources  :orders,      only:[:index,:show,:update]
    resources  :order_lists, only:[:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
end

app/models/order.rb
class Order < ApplicationRecord

  enum status: { '入金待ち': 0, '入金確認': 1, '製作中': 2, '発送準備中': 3, '発送済み':4 }
  enum payment_method: { 'クレジット': 0, '銀行振込': 1 }

  with_options presence: true do
    validates :customer_id
    validates :postage
    validates :total_price
    validates :postcode
    validates :address
    validates :address_name
    validates :payment_method
    validates :status
  end

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  attr_accessor :shipping_sel,:shipping_address_id

  #追加メソッド

  #注文個数の合計を返す
  def order_quantity_count
    order_details = OrderDetail.where(order_id: self.id)
    count = 0
    order_details.each do |order_detail|
      count += order_detail.quantity
    end
    return count
  end

  #送料含む総額を返す
  def amount_including_shipping
    self.total_price + self.postage
  end

  #紐づく商品名を返す
  def detail_items
    arry = []
    OrderDetail.where(order_id: self.id).each do |order_detail|
      arry.push(order_detail.item.name)
    end
    return arry
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    if customer_id = params[:customer_id]
      @orders = Order.where(customer_id: customer_id).page(params[:page]).reverse_order
    else
      @orders = Order.page(params[:page]).reverse_order
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end

  def update
    @order = Order.find(params[:id])
    @order.status = params[:order_status]
    @order.save
    @order_details = OrderDetail.where(order_id: @order.id)
    #注文詳細の製作ステータスを更新
    if @order.status == "入金確認"
      @order_details.each do |order_detail|
        order_detail.status = "製作待ち"
        order_detail.save
      end
    end
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_order_detail_status.html.erb
<% order_details.each do |order_detail| %>
  <tr>
    <td><%= order_detail.item.name %></td>
    <td><%= order_detail.unit_price.to_s(:delimited) %></td>
    <td><%= order_detail.quantity %></td>
    <td><%= order_detail.price.to_s(:delimited) %></td>
    <td>
      <%= form_with url: admin_order_list_path(order_detail.id), class:"form-inline text-nowrap", method: :PATCH, remote: true do |f| %>
        <% if order_detail.status == "着手不可" %>
          <%= f.select :order_detail_status, [["着手不可", "着手不可"]], {}, style:"width: 120px", class:"form-control" %>
        <% elsif order_detail.status == "製作待ち" %>
          <%= f.select :order_detail_status, [["製作待ち", "製作待ち"],["製作中", "製作中"]], {}, style:"width: 120px", class:"form-control" %>
        <% elsif order_detail.status == "製作中" %>
          <%= f.select :order_detail_status, [["製作中", "製作中"],["製作完了", "製作完了"]], {}, style:"width: 120px", class:"form-control" %>
        <% elsif order_detail.status == "製作完了" %>
          <%= f.select :order_detail_status, [["製作完了", "製作完了"]], {}, style:"width: 120px", class:"form-control" %>
        <% end %>
        <%= f.submit '更新', class:"btn-flat-success ml-4" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/orders/_order_status.html.erb
<div class="form-group">
  <%= form_with url: admin_order_path(order), class:"form-inline", method: :PATCH,  remote: true do |f| %>
    <% if order.status == "入金待ち" %>
      <%= f.select :order_status, [["入金待ち", "入金待ち"], ["入金確認", "入金確認"]], {}, style:"width: 140px", class:"form-control" %>
    <% elsif order.status == "入金確認" %>
      <%= f.select :order_status, [["入金確認", "入金確認"]], {}, style:"width: 140px", class:"form-control" %>
    <% elsif order.status == "製作中" %>
      <%= f.select :order_status, [["製作中", "製作中"]], {}, style:"width: 140px", class:"form-control" %>
    <% elsif order.status == "発送準備中" %>
      <%= f.select :order_status, [["発送準備中", "発送準備中"], ["発送済み", "発送済み"]], {}, style:"width: 140px", class:"form-control" %>
    <% elsif order.status == "発送済み" %>
      <%= f.select :order_status, [["発送済み", "発送済み"]], {}, style:"width: 140px", class:"form-control" %>
    <% end %>

    <%= f.submit '更新', class:"btn-flat-success ml-4" %>
  <% end %>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-3">
      <h5 class="two-line-heading">注文履歴一覧</h5>
      <table class='table table-hover w-100'>
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <th>
                <u><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order), class:'link_animation' %></u>
              </th>
              <th><%= order.customer.join_name %></th>
              <th><%= order.order_quantity_count %></th>
              <th><%= order.status %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="two-line-heading">注文履歴詳細</h5>
  </div>

  <div class="row mt-3">
    <table class="w-100">
      <tbody>
        <tr>
          <th class="pb-2 pt-2 col-4 col-md-3 col-lg-2 font-weight-normal">購入者</th>
          <td class="pt-2">
            <u><%= link_to @order.customer.join_name, admin_customer_path(@order), class:"link_animation" %></u>
          </td>
        </tr>
        <tr>
          <th class="pt-2 col-4 col-md-3 col-lg-2 font-weight-normal">注文日</th>
          <td class="pt-2"><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th class="pt-2 col-4 col-md-3 col-lg-2 font-weight-normal">配送先</th>
          <td class="pt-2">
            <span>〒<%= @order.postcode %> <%= @order.address %></span><br>
            <span><%= @order.address_name %></span>
          </td>
        </tr>
        <tr>
          <th class="pt-2 col-4 col-md-3 col-lg-2 font-weight-normal">支払方法</th>
          <td class="pt-2"><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th class="pt-2 col-4 col-md-3 col-lg-2 font-weight-normal">注文ステータス</th>
          <td class="pt-2" id="admin_orders_show_order_status">
            <%= render 'order_status', order: @order %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class='row mt-3'>
    <div class='col-12 col-lg-8'>
      <div class="table-responsive">
        <table class='table'>
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
            </tr>
          </thead>
          <tbody id="admin_orders_show_order_detail_status">
            <%= render 'order_detail_status', order_details: @order_details %>
          </tbody>
        </table>
      </div>
    </div>
    <div class='col-7 col-sm-6 col-md-4 col-lg-3'>
      <div class="table-responsive">
        <table class='table table-borderless'>
          <tbody>
            <tr>
              <th class="font-weight-normal">商品合計</th>
              <td class="text-right"><%= @order.total_price.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th class="font-weight-normal">送料</th>
              <td class="text-right"><%= @order.postage.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th class="font-weight-normal">請求額合計</th>
              <td class="text-right"><%=@order.amount_including_shipping.to_s(:delimited) %>円</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.js.erb
$("#admin_orders_show_order_status").html("<%= j(render "admin/orders/order_status", order: @order) %>");
$("#admin_orders_show_order_detail_status").html("<%= j(render "admin/orders/order_detail_status", order_details: @order_details) %>");