config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    root 'homes#top'
    get  'about',   to: 'homes#about'

    resource  :customers,     only:[:show,:edit,:update] do
        get   'quit_confirm', on: :collection
        patch 'quit',         on: :collection
    end

    resources :shipping_addresses, except:[:new,:show]
    resources :items,              only:[:index,:show] do
      get :autocomplete_item_name, :on => :collection
    end

    resources :cart_items, except:[:new,:edit,:show] do
      delete 'destroy_all', on: :collection
    end

    resources :orders, only:[:create,:index,:show] do
      collection do
        get  'information'
        get  'thankyou'
        post 'purchase'
      end
    end
  end

  namespace :admin do
    resources  :customers,   except:[:new,:destroy,:create]
    resources  :genres,      except:[:new,:destroy,:show]
    resources  :items,       except:[:destroy]
    resources  :orders,      only:[:index,:show,:update]
    resources  :order_lists, only:[:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
end

app/views/layouts/_errors.html.erb
<div class='container'>
  <div class='row mt-3'>
    <div class='col'>
      <% if obj.errors.any? %>
        <h4><%= obj.errors.count %>件のエラーが発生しました。</h4>
        <ul>
          <% obj.errors.full_messages.each do|message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/efe3d01fd5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <% if admin_signed_in? %>
            <a class="navbar-brand" href="/admin/orders"><%= image_tag "logo.jpeg", size:"150" %></a>
          <% else %>
            <a class="navbar-brand" href="/"><%= image_tag "logo.jpeg", size:"150" %></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto d-flex align-items-start">
              <li class="nab-link mr-3">
                <% if customer_signed_in? %>
                    W e l c o m e , </br>
                    <%= current_customer.join_name %>
                <% end %>
              </li>
              <% if customer_signed_in? %>
                <li class="nav-item">
                  <%= link_to "M y P a g e", customers_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "I t e m", items_path, class: " nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "C a r t", cart_items_path, class: " nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "L o g o u t", destroy_customer_session_path, method: :delete, class: "nav-link text-dark" %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Item", admin_items_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Customer", admin_customers_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Order", admin_orders_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Genre", admin_genres_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "nav-link text-dark" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "A b o u t", about_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "I t e m", items_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "S i g n u p", new_customer_registration_path, data: {"turbolinks" => false}, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "L o g i n", new_customer_session_path, class: "nav-link text-dark" %>
                </li>
              <% end %>

              <li class="search_form">
                <%= form_with(url: items_path, method: :get, enforce_utf8: false, local: true) do |f| %>
                  <%= f.text_field :search_word , class:"search_form_text" %>
                  <%= f.button :type => "submit", class:"search_form_btn" do %>
                    <i class="fas fa-search search_form_icon"></i>
                  <% end %>
                  <!--<= autocomplete_field_tag 'item[name]', nil,  autocomplete_item_name_items_path %>-->
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>


    <main>
      <div class="container">
        <div class="row my-2">
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
          <div class="text-success">
            <% if flash[:notice] %>
              <div class="flash">
                <%= flash[:notice]%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
      <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
    </main>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <footer class="foot">CopyRight GifuRevengers.inc</footer>
        </div>
      </div>
    </div>

  </body>
</html>